version: 2.1

orbs:
  node: circleci/node@4.7
  coverage-reporter: codacy/coverage-reporter@13.10.8
  codecov: codecov/codecov@3.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests coverage
          command: npm run coverage
      - coverage-reporter/send_report:
          coverage-reports: 'coverage/clover.xml,coverage/lcov.info'
          project-token: $CODACY_PROJECT_TOKEN

workflows:
  release:
    jobs:
      - build-and-test
  upload-to-codecov:
    jobs:
      - build-and-test:
          post-steps:
            - codecov/upload:
                file: 'coverage/clover.xml,coverage/lcov.info'
